/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 specials.gltf 
Author: vanj.creation.photo (https://sketchfab.com/vanj.creation.photo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/popsicle-ice-cream-isometric-c34b893d6e7c4267abad4b4fc79ff01a
Title: Popsicle Ice Cream Isometric
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useThree } from '@react-three/fiber';
// @ts-ignore
export function Special(props) {
  const { nodes, materials } = useGLTF('/model/specials.gltf')
  const { camera } = useThree();
  // Set the initial camera position for zoom
  camera.position.set(0, 0, 8);
  return (
    <group {...props} dispose={null} position={[2,-5,-3]}>
      <group rotation={[-1.518, -0.351, 3.131]} scale={1}>
       {/* @ts-ignore */}
        <mesh  geometry={nodes.Object_2.geometry} material={materials.material} />
        {/* @ts-ignore */}
        <mesh geometry={nodes.Object_3.geometry} material={materials.Stick} />
      </group>
    </group>
  )
}

useGLTF.preload('/model/specials.gltf')
